### PR TITLE
Add swarm activity stats to /.json.

### PR DESCRIPTION
**Pull request by jthuraisamy**
Some may find it useful to view this information outside the CLI. It's not a critical feature, so I'll respect your choice on whether to merge it or not. Thanks for the work so far!

### CODE REVIEW

**Comment by mafintosh** [comment]
it seems this returns the stats for all file entries? i think we should move the stats to the top level and have the files array be a `files` property

``` js
{
  downloaded: ...
  // more stats
  files: [
    name: '...',
    url: ...
    // more file stuff
  ]
}
```

**Comment by jthuraisamy** [comment]
Done. Is there a way for each file entry to have a `downloaded` property?

**Comment by mafintosh** [comment]
No, currently there isn't but we could add that to torrent-stream at some point

**Comment by mafintosh** [comment]
Thanks for the PR! Released in 0.29.0

**Comment by jthuraisamy** [comment]
Thanks for accepting it!

**Pull request merged**
