### PR TITLE
Added native support for Beamer, VPlayer with quality stream to apple TV

### PR DESCRIPTION
**Pull request by hkraji**
Added support for Beamer application (http://beamer-app.com/) I've found that native Airplay support is lacking and error prone, Beamer does far better job and flawlessly streams to Apple TV.

This is my first piece of node.js code, and I would be willing to tweak it if constructive input is provided.

### CODE REVIEW

**Comment by JacopKane** [comment]
Sorry to bring this up but any news on this or Apple TV matter?

**Comment by pnewell** [comment]
Any chance of this working or happening?

**Comment by hongkongkiwi** [comment]
I use beamer and it's a fantastic option, would recommend to support this.

**Comment by hkraji** [comment]
More realistic alternative provided with this PR https://github.com/mafintosh/peerflix/pull/273

**Pull request closed without merging**
