### PR TITLE
Deleted read-torrent

### PR DESCRIPTION
**Pull request by deamme**
TODO was not to use read-torrent but it's now using https://github.com/feross/simple-get instead.

### CODE REVIEW

**Comment by mafintosh** [comment]
@deamme do you know if simple-get inflates gzipped http requests? other than that this is LGTM

**Comment by feross** [comment]
I know the answer – yep. simple-peer handles gzip or deflate responses from the server :+1:

**Comment by mafintosh** [comment]
@feross almost did the same typo you just did when writing simple-get as well

**Comment by mafintosh** [comment]
@deamme LGTM - could you update this PR so it merges against the master branch?

**Comment by feross** [comment]
@mafintosh lol

**Comment by deamme** [comment]
@mafintosh is this not already fixed with parse-torrent?

**Comment by mafintosh** [comment]
@deamme lol yea you're right.

**Pull request closed without merging**
